package rules

import com.micro.model.Address;
import com.micro.model.AddressCheckResult;

rule "Postcode should be filled with exactly 5 numbers"
    no-loop true
    when
        address : Address(postcode != null, postcode matches "([0-9]{5})")
        checkResult : AddressCheckResult();
    then
        address.setStreet("adfafadf");
        checkResult.setPostCodeResult(true);
        System.out.println("规则中打aa印日志：校验通过!");
end
