dubbo:
  application:
    name: mysql
    version: 1.0.0
  protocol:
    name: dubbo
    port: 20883
  provider:
    timeout: 5000
  consumer:
    timeout: 5000
    retries: -1
  registry:
    address: zookeeper://10.5.2.74:2181
server:
  port: 8103

spring:
  data:
    mongodb:
      database: testdb
      host: 127.0.0.1
      port: 27017
logger:
  redis:
    host: 10.5.2.56
  path: /home/jolin/log



