dubbo:
  application:
    name: elasticsearch
    version: 1.0.0
  protocol:
    name: META-INF.dubbo
    port: 20883
  provider:
    timeout: 5000
  registry:
   address: zookeeper://10.5.2.74:2181
server:
  port: 8103



