dubbo:
  application:
    name: elasticsearch
    version: 1.0.0
  protocol:
    name: dubbo
    port: 20881
  provider:
    timeout: 5000
  consumer:
    timeout: 5000
  registry:
    address: zookeeper://10.5.2.74:2181
  monitor:
    address: 10.5.2.27:7070
server:
  port: 8101
spring:
  data:
    elasticsearch:
      cluster-name: es_cluster
      cluster-nodes: 10.5.2.74:9300
      cluster-high-nodes: 10.5.2.74:9200
      repositories:
        enabled: true
logger:
  redis:
    host: 10.5.2.56
  path: /home/jolin/log

